[run]
timeout = "10m"

[linters-settings.golint]
min-confidence = 3

[linters-settings.goconst]
min-len = 5
min-occurrences = 5

[linters]
disable-all = true
enable = [
  "bodyclose",
  "deadcode",
  "depguard",
  "dogsled",
  "errcheck",
  "gochecknoinits",
  "goconst",
  "gocritic",
  "goimports",
  "golint",
  "goprintffuncname",
  "gosec",
  "gosimple",
  "govet",
  "ineffassign",
  "misspell",
  "nakedret",
  "rowserrcheck",
  "exportloopref",
  "staticcheck",
  "structcheck",
  "stylecheck",
  "typecheck",
  "unconvert",
  "unused",
  "varcheck",
  "whitespace",
  "gocyclo",
  "unparam",
]
