[run]
timeout = "10m"

[linters-settings.golint]
min-confidence = 3

[linters-settings.goconst]
min-len = 5
min-occurrences = 5

[linters-settings.depguard.rules.main]
allow = [
  "fmt", "strconv", "time", "net/http",
  "bytes", "io", "math",
  "github.com/go-openapi/runtime",
  "github.com/grafana/grafana-openapi-client-go/pkg/errors",
  "github.com/grafana/grafana-openapi-client-go/pkg/transport"
]

[linters]
disable-all = true
enable = [
  "bodyclose",
  "depguard",
  "dogsled",
  "errcheck",
  "gochecknoinits",
  "goconst",
  "gocritic",
  "goimports",
  "goprintffuncname",
  "gosec",
  "gosimple",
  "govet",
  "ineffassign",
  "misspell",
  "nakedret",
  "rowserrcheck",
  "exportloopref",
  "staticcheck",
  "stylecheck",
  "typecheck",
  "unconvert",
  "unused",
  "whitespace",
  "gocyclo",
  "unparam",
]
